// /lib/question-map.js
// AUTO-GENERATED by scripts/regenerate-question-map.js
// Regenerated: 2026-05-25T10:15:27.975Z
// Source: https://api.leadconnectorhq.com/widget/survey/E8iUexhy9T4qKYMylUPb
//
// Maps each GHL custom field ID to its question position (sr_qN) and ordered
// picklist options. The scoring layer uses the option index to determine the
// tag for that answer. To refresh after the survey changes in GHL, run:
//   npm run regenerate-question-map

module.exports = {
  QUESTION_MAP: {
    // Q  1: When you walk into a new room of people, you tend to:
    "xUTEoMUHLWtrZaMKyjFY": { qnum: 1, options: ["Take charge of the conversation", "Greet everyone with energy and humor", "Quietly observe before engaging", "Notice the details others miss"] },
    // Q  2: Under pressure, your first instinct is to:
    "qAibKOQ2ZUkB1YEIJmxE": { qnum: 2, options: ["Push harder and decide faster", "Rally people and lift the mood", "Stabilize the room and keep things calm", "Step back and analyze the situation"] },
    // Q  3: When making a big decision, you most trust:
    "odHQDoa4ZbbEdwajctJm": { qnum: 3, options: ["Your gut and your goal", "Your conversations with people you trust", "Your sense of what feels stable and right", "The data and the facts"] },
    // Q  4: People who frustrate you the most are usually:
    "NSqCtp4p0WS9LfVXfsRs": { qnum: 4, options: ["Indecisive or slow", "Cold, unfriendly, or negative", "Aggressive, pushy, or unpredictable", "Sloppy, careless, or vague"] },
    // Q  5: When you give feedback to someone, you tend to:
    "Fh3gOEiuS5rZGLCRKc6R": { qnum: 5, options: ["Get straight to the point, no softening", "Lead with encouragement and warmth", "Choose your words carefully to protect the bond", "Lay out specific facts and examples"] },
    // Q  6: When a project goes off the rails, your role is usually:
    "ysSMn2XCmd0IeuEFY1qL": { qnum: 6, options: ["Take command and reset the direction", "Re-energize the team and rebuild morale", "Hold things together and protect what works", "Diagnose what went wrong and fix the system"] },
    // Q  7: Your office or workspace tends to be:
    "JIftaZHroJzVt7hNnIMW": { qnum: 7, options: ["Functional, results-focused, minimal", "Personal, full of photos and energy", "Comfortable, organized for routine", "Precise, organized for accuracy"] },
    // Q  8: When you are wrong, you:
    "eIVQYo8sfhkMgKKwlFLR": { qnum: 8, options: ["Acknowledge it fast and move forward", "Laugh at yourself and own it openly", "Apologize quietly and reflect on it", "Trace back to find exactly where the error happened"] },
    // Q  9: You are most energized by:
    "nFRv6H1cPW0QP5Okdppl": { qnum: 9, options: ["Winning. Achieving the goal.", "Connecting. Inspiring people.", "Helping. Serving consistently.", "Solving. Getting it exactly right."] },
    // Q 10: In a meeting, you are most likely to:
    "AveCYqkerwHFOKLCoN9Q": { qnum: 10, options: ["Drive the agenda and push for decisions", "Build the energy and bring others in", "Listen carefully and support the group", "Ask the questions that surface what's missing"] },
    // Q 11: Your biggest weakness when leading others is:
    "Ij2BdHt0slO14ZedkDgt": { qnum: 11, options: ["Steamrolling people who think slower than you", "Avoiding the hard conversations to keep the peace", "Tolerating bad behavior longer than you should", "Getting stuck in analysis and missing the moment"] },
    // Q 12: When someone challenges you publicly, you:
    "WkK9dygHT8bUfAVZVUI5": { qnum: 12, options: ["Push back hard, immediately", "Charm them and reframe the room", "Stay calm and let it pass", "Quietly note their argument and respond with logic later"] },
    // Q 13: Your sense of "winning" looks most like:
    "ZKtpxOQ5e2WejZ3nY1DI": { qnum: 13, options: ["Hitting the target on time", "Building a movement of believers", "Knowing your people are safe and cared for", "Producing work that holds up to scrutiny"] },
    // Q 14: You feel most drained by:
    "Qss1TdXpViygiFfrtb8f": { qnum: 14, options: ["Endless meetings without decisions", "Cold, transactional environments", "Sudden change without warning", "Sloppy work and unclear expectations"] },
    // Q 15: Your tagline if you had one would be:
    "7TvQiVxraqGAeEnok52U": { qnum: 15, options: ["\"Get it done.\"", "\"Let's go together.\"", "\"I've got you.\"", "\"Let's make sure we get it right.\""] },
    // Q 16: When a deadline is at risk, you:
    "bjuj2OXK5lG5ESjVByHA": { qnum: 16, options: ["Push harder and demand faster output", "Pump up the team and rally them through it", "Quietly pick up the slack to protect them", "Rework the plan and re-sequence the tasks"] },
    // Q 17: Your worst meeting is one with:
    "PSQHUfeihJ8DtKAiSFvU": { qnum: 17, options: ["Too much discussion, not enough action", "Tense silence and awkward energy", "Surprises and uncomfortable confrontation", "Fuzzy thinking and unsupported claims"] },
    // Q 18: When you hire someone, you look for:
    "PIgdG26xJYuucfH7sBHF": { qnum: 18, options: ["A track record of results", "Energy, charisma, and culture fit", "Loyalty, reliability, and steady character", "Precision, expertise, and high standards"] },
    // Q 19: A perfect Saturday for you is:
    "VuRBUIFfBGOPxI37jRGu": { qnum: 19, options: ["Knocking out a list of things you've been putting off", "Being around the people who light you up", "A slow morning, no agenda, comfort food", "Diving deep into a project, learning something new"] },
    // Q 20: Your texting style is:
    "yf2HRSuUzB9cTGX5pwR0": { qnum: 20, options: ["Short. Direct. Often without punctuation.", "Lots of emojis, voice notes, exclamation points", "Warm, considerate, checking on the other person", "Carefully composed, complete sentences"] },
    // Q 21: You are most uncomfortable with:
    "GXIK2GbF5UtHtNrKi3H2": { qnum: 21, options: ["Being told to slow down", "Being ignored or talked over", "Being put on the spot", "Being asked to act on incomplete data"] },
    // Q 22: When you are in love or close friendship, you express it by:
    "B3x3eaIAAgo9D7Cqj5Zy": { qnum: 22, options: ["Solving their problems", "Being playful, present, fun to be with", "Showing up consistently, no matter what", "Knowing them deeply and remembering details"] },
    // Q 23: A coworker says about you behind your back:
    "nI8L1VEGuGzjYVZsQRvP": { qnum: 23, options: ["\"She gets things done. Don't get in her way.\"", "\"He's the heart of the team. Everyone loves him.\"", "\"She's the rock. We'd fall apart without her.\"", "\"He catches what nobody else does.\""] },
    // Q 24: If your behavior had a default setting under stress, it would be:
    "5gzfsRUVK39Iz6yWTgBL": { qnum: 24, options: ["Fight. Push back. Take control.", "Charm. Smooth it over. Find allies.", "Freeze. Wait it out. Hope it passes.", "Withdraw. Analyze. Build the case."] },
    // Q 25: After a long day with people, you feel:
    "YuvnxYNfq9cZuKb3Z6Tr": { qnum: 25, options: ["Energized and ready for more", "Drained, needing time alone to recover"] },
    // Q 26: When making a tough call, you weigh:
    "Aew0belbN46Kj4YNZngu": { qnum: 26, options: ["The concrete facts and proven examples", "People, values, and emotional impact"] },
    // Q 28: Your daily life works best when:
    "T8RXqD9M7d9L0v47DMjW": { qnum: 28, options: ["Plans are made and decisions are settled", "Things stay open and adaptable"] },
    // Q 29: A friend describes you as:
    "bq4XSMg57RKwK5UWEwXQ": { qnum: 29, options: ["Outgoing and expressive", "Thoughtful and reserved"] },
    // Q 30: When learning something new, you trust:
    "4rZvX5r7oISRnKelAguN": { qnum: 30, options: ["Hands-on experience and step-by-step instructions", "The big-picture concept first, details later"] },
    // Q 31: When someone hurts your feelings, your first response is
    "YO0faSHJojXIICgwz8De": { qnum: 31, options: ["To analyze why it happened", "To feel the weight of it and process the emotion"] },
    // Q 32: Your ideal weekend looks like
    "TWD2Xa2OHUufjEd3XDVa": { qnum: 32, options: ["Plans set in advance, knowing what's happening", "Open with options, deciding as you go"] },
    // Q 33: In a group conversation, you:
    "uzw6WkFw2HAoZ0SYYW9X": { qnum: 33, options: ["Speak up often, think out loud", "Listen more, speak when you have something specific to say"] },
    // Q 34: You are more interested in
    "vCSIz6cIhKo9D7Ug6yFd": { qnum: 34, options: ["What is, in front of you, real and present", "What could be, behind the surface, possible"] },
    // Q 35: When giving advice, you usually
    "Fc1EDlT9DAffnDiytsT5": { qnum: 35, options: ["Tell people the honest truth, even if it stings", "Consider how they'll feel and frame it gently"] },
    // Q 36: A surprise change of plans makes you feel:
    "GhgCgqY952vZFVsyIDUY": { qnum: 36, options: ["Anxious or annoyed, you wanted the original", "Curious or excited, new options just opened"] },
    // Q 37: You recharge best by:
    "Vja0WbOnWOXKlte5ewxv": { qnum: 37, options: ["Being around people you love", "Being alone with your thoughts"] },
    // Q 38: You trust
    "q3lMyNoO5zeh3l4ib3n6": { qnum: 38, options: ["Experience and what has worked before", "Intuition and what could work next"] },
    // Q 39: A workplace decision should be made based on:
    "3sbKJgn2sRh938FRrMdB": { qnum: 39, options: ["Objective performance metrics", "The wellbeing and growth of the people involved"] },
    // Q 40: When attending an event, you prefer: 
    "2KOMy4KLu8ldqQ9Y0d09": { qnum: 40, options: ["A clear schedule of what's happening when", "An open agenda where things can unfold naturally"] },
    // Q 41: Parties drain you faster when:
    "wUm0HpQY2lhdKSSuGRbX": { qnum: 41, options: ["You don't know enough people", "You can't move around and meet new people"] },
    // Q 42: A book is more interesting to you if it:
    "pTbkiiJFSeiWduL9Fyl9": { qnum: 42, options: ["Is grounded in real, lived experience", "Explores ideas, theory, and what could be"] },
    // Q 43: Conflict is best handled by:
    "oPrxhxIl87JR2wyTfkrq": { qnum: 43, options: ["Naming the issue clearly and resolving it logically", "Hearing everyone's perspective and feelings first"] },
    // Q 44: Your bedroom or living space is:
    "IIesGeVtgKuPqK0pbR7J": { qnum: 44, options: ["Tidy, organized, things in their place", "Lived-in, spontaneous, with stuff around you love"] },
    // Q 45: You'd rather work:
    "HUTC13Qlwj2E44wI8x8a": { qnum: 45, options: ["In a team where ideas bounce off each other", "Alone with focused, uninterrupted time"] },
    // Q 46: Your most useful skill is:
    "OJ95xZOfcyrJvXdO3Htn": { qnum: 46, options: ["Noticing the practical thing that needs doing", "Spotting the connection nobody else has seen"] },
    // Q 47: A leader is great because:
    "xstHW1raqnZO4gQdi4xY": { qnum: 47, options: ["They make the right call under pressure", "They make people feel seen and valued"] },
    // Q 48: Deadlines feel:
    "1Jt5OWhb8xXOUj7DRlur": { qnum: 48, options: ["Like helpful structure that drives focus", "Like artificial pressure that limits creativity"] },
    // Q 49: You communicate best:
    "9IKUSI0xj5qOFzSH3Gxy": { qnum: 49, options: ["In real-time conversation", "In writing, after thinking"] },
    // Q 50: Your most common phrase about the future is:
    "M7QjlnS31MPNLGOCkuDl": { qnum: 50, options: ["Let's see what's actually possible.", "Imagine if..."] },
    // Q 51: When someone makes a mistake at work:
    "MhxufhgRaO9R6SOxMiH1": { qnum: 51, options: ["Address it directly so it doesn't happen again", "Find a way to address it that keeps them encouraged"] },
    // Q 52: Your to-do list:
    "DpPEZJsEl9PKKDaP6kGm": { qnum: 52, options: ["Exists, gets followed, gets crossed off", "Exists somewhere, gets ignored, life still works"] },
    // Q 53: Faced with a new project, your first instinct is:
    "g61zMHB99se0yaVHHOZe": { qnum: 53, options: ["Research everything you can find about it", "Map out the steps and make a plan", "Start moving and figure it out as you go", "Sketch it, prototype it, build something you can touch"] },
    // Q 54: Your friends call you when they need:
    "dw5vZCeaqN2cJYrkkZ81": { qnum: 54, options: ["Someone to dig into the facts and tell them what's true", "Someone to organize the chaos into a system", "Someone to throw out wild ideas and try things", "Someone to actually fix the broken thing"] },
    // Q 55: A task feels most satisfying when:
    "wFPdd9psj0uMzzdbFHiq": { qnum: 55, options: ["You uncover the answer nobody else found", "The whole thing runs like a well-oiled machine", "You moved fast and made something happen", "You can hold the finished thing in your hands"] },
    // Q 56: At work, your reputation is:
    "dvhfWQJpp6XA1ZEs0WcV": { qnum: 56, options: ["The one who knows where everything is documented", "The one who keeps everything on track", "The one who pushes through when others stall", "The one who can build, fix, or make anything"] },
    // Q 57: When stuck on a hard problem, you:
    "4KEFNM5Brq5kttS6D2e0": { qnum: 57, options: ["Read three more articles before you decide", "Build a checklist and work through it methodically", "Try something, anything, and adjust", "Take it apart with your hands and see how it works"] },
    // Q 58: You hate when:
    "qzjc0EpIw4zw4PGKfQkd": { qnum: 58, options: ["Someone makes a claim without evidence", "The plan keeps changing and nothing settles", "You have to wait for permission to move", "Nobody actually builds the thing, they just talk"] },
    // Q 59: Your idea of a productive Saturday:
    "Uw9YKNndnnKik9NgSF8Z": { qnum: 59, options: ["A deep dive into a topic you've been curious about", "Knocking out a list of organized errands", "Spontaneously doing something new", "Working with your hands on a project"] },
    // Q 60: You'd rather be known for:
    "KET7t2cDwUynD9wWMc4l": { qnum: 60, options: ["Being right", "Being thorough", "Being bold", "Being capable"] },
    // Q 61: When asked to estimate how long something will take:
    "9d0BvIGCE9yODDSoUc39": { qnum: 61, options: ["You pull historical data and give a careful answer", "You build a step-by-step timeline and pad it", "You shrug and say \"let's start and find out\"", "You think about what tools you'd need and estimate from there"] },
    // Q 62: Your phone or notebook is full of:
    "XQX9aE9aaNOKJtkXJzIr": { qnum: 62, options: ["Articles, links, research you've saved", "Lists, calendars, structured notes", "Ideas, possibilities, things you might try", "Photos of things you've made or want to build"] },
    // Q 63: When the team is brainstorming, you contribute:
    "BKUEEJf47Dh2QuZATqor": { qnum: 63, options: ["The data point everyone else missed", "The framework that makes the ideas usable", "The wild idea that opens new doors", "The \"here's how we'd actually build that\" insight"] },
    // Q 64: Your home improvement style:
    "JStXo8jrB2HD5gU90hiK": { qnum: 64, options: ["Research the heck out of every option before deciding", "Plan it out, schedule it, execute it cleanly", "Buy the materials and start swinging the hammer", "Do it yourself with your hands, learn as you go"] },
    // Q 65: You learn best by:
    "0vwDLbjULeSvukA49hbA": { qnum: 65, options: ["Reading deeply about it", "Following a structured course", "Trying it and failing your way through", "Doing it physically with someone showing you"] },
    // Q 66: When the system breaks down:
    "zeFuxn9Nm9IYKcJrsELe": { qnum: 66, options: ["You investigate why before doing anything", "You document what failed and rebuild the process", "You find a workaround fast and keep moving", "You roll up your sleeves and fix the actual thing"] },
    // Q 67: A coworker describes your work style as:
    "sOwsH6wOBeEjjKO146pJ": { qnum: 67, options: ["Detail-obsessed in a good way", "Organized, structured, dependable", "Energetic, unpredictable, fast", "Hands-on, practical, gets it done"] },
    // Q 68: You're least comfortable when asked to:
    "BsStIYaavSKgWVW6d9q9": { qnum: 68, options: ["Make a call without enough information", "Improvise without a plan", "Sit and analyze when action is needed", "Talk about doing it instead of doing it"] },
    // Q 69: A satisfying win looks like:
    "hIgJJreR5LJr4NNWl8oF": { qnum: 69, options: ["\"We finally have the right answer\"", "\"The system is running smoothly\"", "\"We tried something nobody else would have\"", "\"We built the thing and it works\""] },
    // Q 70: Your bookshelf is mostly:
    "1jSi5qYTAvEUqHDKefD4": { qnum: 70, options: ["Reference books and deep nonfiction", "How-to manuals and structured frameworks", "Idea books, possibility, big-picture thinking", "Practical guides for building things"] },
    // Q 71: When a meeting wraps up, you want:
    "Kf5rKpN6C23cEtupeADP": { qnum: 71, options: ["A summary of what we now know", "A clear list of next steps and owners", "Permission to start moving on something", "Agreement on what we're actually going to build"] },
    // Q 72: Your superpower at work is:
    "i2Jnyyd27xkYkZBDw0jz": { qnum: 72, options: ["Finding the truth nobody else dug up", "Turning chaos into structure", "Moving when others are paralyzed", "Making the thing real"] },
    // Q 73: You feel most loved when someone:
    "RCw1SyrJUKOuJSbwCslp": { qnum: 73, options: ["Tells you what they appreciate about you", "Spends focused time with you, no distractions", "Does something practical to help you", "Brings you something thoughtful for no reason", "Holds you, hugs you, rests their hand on yours"] },
    // Q 74: When a friend is hurting, you:
    "1c53rD19xG1aKTkWlV3D": { qnum: 74, options: ["Send a long, thoughtful message about who they are", "Show up and just be there with them", "Drop off food, run their errands, fix the thing", "Bring them something small that says \"I see you\"", "Hug them long and hard"] },
    // Q 75: You feel disconnected in a relationship when:
    "6yPbRdf0mBhLbkjFRkMc": { qnum: 75, options: ["Compliments and \"I love you\" stop happening", "You're in the same room but never actually present together", "They stop helping with the things that weigh on you", "Birthdays, holidays, milestones get forgotten", "The physical closeness fades"] },
    // Q 76: The most romantic thing someone could do for you:
    "S9HKUIpCfQZ5iOm6OmQQ": { qnum: 76, options: ["Write you a letter explaining what you mean to them", "Plan a whole day with you, just the two of you", "Take care of something that's been stressing you out", "Surprise you with a meaningful gift", "Slow dance in the kitchen"] },
    // Q 77: You give love mostly by:
    "jEXOBV93GsIuxO2E7mSO": { qnum: 77, options: ["Saying it out loud, often", "Carving out time to be fully present", "Doing things that make their life easier", "Picking out something they'd love and giving it", "Reaching for them, touching them, holding them"] },
    // Q 78: A small act that means more than people realize:
    "YJotaJj0auCd5QRNFISN": { qnum: 78, options: ["Telling someone they did a great job, specifically", "Putting your phone down when they walk in", "Filling up their gas tank without being asked", "Bringing home their favorite snack", "A hand on the shoulder when they're stressed"] },
    // Q 79: Criticism hurts you most when:
    "WUFnjBqpPAUp01am6oX2": { qnum: 79, options: ["Someone says cruel words", "Someone gives you the silent treatment", "Someone refuses to help when you need it", "Someone \"forgets\" you on important occasions", "Someone pulls away physically"] },
    // Q 80: Your ideal partner reminds you they love you by:
    "D6BggpCoXkYS6OBOwhJd": { qnum: 80, options: ["Telling you, often, in words you remember", "Choosing you over other plans, again and again", "Anticipating what you need and handling it", "Marking moments with thoughtful tokens", "Always touching you in passing"] },
    // Q 81: After a long day, you most want:
    "GyTa5dKwapZT63N48VFC": { qnum: 81, options: ["Someone to tell you you did well", "Someone to sit with you and ask how it went", "Someone to take dinner off your plate", "A small surprise waiting at home", "A long, real hug"] },
    // Q 82: You'd be most disappointed if your partner:
    "LExVvPumKvDkGryqmvVL": { qnum: 82, options: ["Stopped saying \"I love you\"", "Always seemed busy when you wanted to talk", "Never noticed when you were overwhelmed", "Forgot every birthday and anniversary", "Stopped being affectionate"] },
    // Q 83: When someone you care about is celebrating, you:
    "23NENjMs6nj3w1zjHOPq": { qnum: 83, options: ["Give a heartfelt toast or write something", "Show up, be there, give them your full attention", "Handle the logistics so they can enjoy it", "Bring a meaningful gift that fits them", "Hug them, kiss their forehead, hold their hand"] },
    // Q 84: A perfect anniversary involves:
    "qWrvztT7IxCG7ysoDLtr": { qnum: 84, options: ["Cards, words, what they mean to you", "Hours of just being together with no distractions", "Them taking care of you the whole day", "A gift that proves they really know you", "Closeness, touching, being physically wrapped up in each other"] },
    // Q 85: You're hardest on yourself when:
    "rPcks1gxai2rbPA3n4mi": { qnum: 85, options: ["You said the wrong thing", "You weren't really present with someone you love", "You let someone down by not following through", "You forgot a birthday or special date", "You weren't physically there when someone needed you"] },
    // Q 86: The phrase that hits home for you:
    "WsskwhTGySiWuvK7rcA6": { qnum: 86, options: ["\"I love hearing what you have to say.\"", "\"I want to spend the day with you.\"", "\"Let me handle that for you.\"", "\"I saw this and thought of you.\"", "\"Come here.\""] },
    // Q 87: When a relationship is going well, you notice:
    "JGtrHKoIow8WQMTcIImG": { qnum: 87, options: ["The compliments and affirmations are flowing", "You're spending real, undistracted time together", "They're helping you carry the weight", "They surprise you with little tokens often", "The physical closeness is constant"] },
    // Q 88: When you give a gift, you usually:
    "RxE1JibENeOumbEAuxvw": { qnum: 88, options: ["Write a card that means more than the gift", "Schedule the giving, make it an experience", "Give something practical they actually need", "Hunt for the perfect, thoughtful thing", "Hand it to them in person, with a hug"] },
    // Q 89: You feel most cared for when someone:
    "vcboEOgvqoESCdN9EuHS": { qnum: 89, options: ["Notices what you said and references it later", "Carves out time to truly listen", "Removes a burden without being asked", "Brings home something that says they were thinking of you"] },
    // Q 90: Texts that make you smile:
    "ZiyvA8ed1EF0vrnaSxOT": { qnum: 90, options: ["I was just thinking how lucky I am to have you", "Free tonight? Just want to be with you", "I already took care of it", "Look what I got you", "Can't wait to hold you"] },
    // Q 91: The hardest thing for you to receive is:
    "IFnr0m6vjFmYJdHKHBbe": { qnum: 91, options: ["Praise (you deflect it but secretly need it)", "Someone's full undivided time", "Help (you'd rather do it yourself)", "A gift, especially an extravagant one", "Physical affection in front of others"] },
    // Q 92: If you had to pick just one to keep:
    "BUSemA0xnmjPwXXvrHqI": { qnum: 92, options: ["Words, kind and consistent", "Time, real and undistracted", "Service, showing up to help", "Gifts, thoughtful and surprising", "Touch, warm and frequent"] },
    // Q 93: When learning something new, you grasp it fastest when:
    "z6KD445lT9gEmGwLnyXB": { qnum: 93, options: ["Someone draws it on a whiteboard", "Someone explains it out loud", "You read about it", "You try it yourself"] },
    // Q 94: You remember directions best when:
    "oL5zERGw20plG8CEPOKL": { qnum: 94, options: ["You see a map", "Someone tells you the turns", "You write them down", "You drive the route once"] },
    // Q 95: A great teacher for you uses:
    "ScynbOYKeYqyAio1iCGD": { qnum: 95, options: ["Diagrams, charts, slides", "Stories, lectures, discussion", "Reading assignments, written notes", "Hands-on labs, demos, practice"] },
    // Q 96: When trying to remember a name, you:
    "VTf25LyftpiyBUlH15UI": { qnum: 96, options: ["Picture the person's face", "Repeat the name out loud", "Write it down", "Associate it with where you met"] },
    // Q 97: Your favorite kind of meeting:
    "qizvtdMt32LchAzkTUzG": { qnum: 97, options: ["Has visuals, slides, a clear agenda on screen", "Is a discussion where ideas get talked through", "Comes with a doc you can read and reference", "Involves doing something, not just talking"] },
    // Q 98: When assembling something, you:
    "ZELAGysGq9Q6JSttEyDj": { qnum: 98, options: ["Look at the picture diagram", "Have someone walk you through it verbally", "Have someone walk you through it verbally", "Skip the instructions and start putting pieces together"] },
    // Q 99: To explain a complex idea, you:
    "Zy085CqQ8CkomxovAanw": { qnum: 99, options: ["Draw it out", "Talk through it step by step", "Write a clear summary", "Write a clear summary"] },
    // Q101: You learn a new song best by:
    "p3ExF6BehVknu0QyZhHg": { qnum: 101, options: ["Watching the music video", "Listening to it over and over", "Reading the lyrics", "Singing or playing it yourself"] },
    // Q102: When stressed about a problem, you:
    "kE0k9fi0TXRI9Z8khYvr": { qnum: 102, options: ["Map it out on paper", "Talk it through with someone", "Journal about it", "Take a walk and let your body work it out"] },
    // Q103: At a museum, you spend the most time:
    "v8DtHbuzTBwlNoGaedgB": { qnum: 103, options: ["Looking at art and exhibits", "On the audio tour", "Reading the placards and pamphlets", "At interactive, hands-on stations"] },
    // Q104: A presentation lands for you when it:
    "3KA3YIoAOisbAFhJth3o": { qnum: 104, options: ["Has clean, beautiful slides", "Is delivered by a great speaker", "Comes with a thorough written handout", "Includes activities or audience participation"] },
    // Q105: When buying something complex (a car, a house), you:
    "sqRIahdlA0A93nCqnQtZ": { qnum: 105, options: ["Compare side-by-side photos and specs visually", "Talk to the salesperson, ask lots of questions", "Read every review and spec sheet", "Test drive it, walk through it, touch everything"] },
    // Q106: Your notes look like:
    "oOCQX0IylJjCj6nPAhHk": { qnum: 106, options: ["Mind maps, doodles, color-coded", "Mostly nothing, you remember by listening", "Pages of structured, written-out notes", "Sparse, because you'd rather just do the thing"] },
    // Q107: When following a recipe, you:
    "LoN30Li8m6HSk5OUtYCj": { qnum: 107, options: ["Want photos of each step", "Want a video where someone talks you through it", "Want clear written instructions", "Want to wing it and adjust as you go"] },
    // Q108: You retain information best when you:
    "n3zRt8e2w9Duec02Nzpw": { qnum: 108, options: ["Saw it presented visually", "Heard it explained well", "Read it carefully", "Did it with your hands"] },
    // Q109: Your spiritual or faith life is best described as:
    "hg6IHBOGGl8t87rqDg32": { qnum: 109, options: ["Active in a specific religious tradition", "Spiritual but not tied to a specific religion", "Curious and exploring, no fixed orientation", "Secular, focused on ethics and meaning without religion"] },
    // Q110: When you face a hard time, you most likely:
    "IkSHMGKXtRME8v4zbxtg": { qnum: 110, options: ["Pray or talk to God", "Meditate or sit in silence", "Talk to a person you trust", "Process it on your own through reflection"] },
    // Q111: A meaningful spiritual practice for you looks like:
    "7aVqTnnXc66zWeZua6Oy": { qnum: 111, options: ["Worship in community with others", "Quiet time alone reading or contemplating", "Service or acts of kindness toward others", "Time in nature"] },
    // Q112: The value that matters most to you:
    "CmsrDuLc6taSiq93lDys": { qnum: 112, options: ["Love, for self and for others", "Truth, even when it's hard", "Service, helping where you can", "Peace, inner and shared"] },
    // Q113: You feel closest to something larger than yourself when:
    "kP11VtavQpOawAJol8X7": { qnum: 113, options: ["You're worshipping or praying", "You're helping someone in need", "You're surrounded by beauty or nature", "You're with people you love"] },
    // Q114: Your spiritual or moral compass came primarily from:
    "fwVEVohbuGvaL67mqJcJ": { qnum: 114, options: ["Religious upbringing and tradition", "Personal experiences and lessons learned", "Mentors, teachers, or wise people in your life", "Books, study, and your own reflection"] },
    // Q115: You handle suffering by:
    "ftip83cQZ14IY8Md2ce6": { qnum: 115, options: ["Surrendering, trusting the bigger picture", "Working through it actively, doing something", "Sitting with it, feeling it fully", "Looking for the meaning or lesson"] },
    // Q116: A perfect spiritual practice would be:
    "Ejb2bQeCviBGs8Uil7Ji": { qnum: 116, options: ["Daily, structured, part of a clear path", "Flexible, intuitive, when the moment calls for it", "Communal, shared with others on the same journey", "Solo, private, just you and the deeper thing"] },
    // Q117: The teacher or thinker you most resonate with is:
    "mcniSy0JzqYfdDx5vz47": { qnum: 117, options: ["Someone deeply rooted in a religious tradition", "Someone modern, integrative, drawing from many sources", "Someone scientific or philosophical", "Someone mystical or contemplative"] },
    // Q118: Your sense of purpose comes most from:
    "zTpKc2seWpZ99DeoViGq": { qnum: 118, options: ["Serving God or a higher calling", "Loving and showing up for the people in your life", "Doing meaningful work in the world", "Growing into the fullest version of yourself"] },
    // Q119: When someone shares a faith different from yours, you:
    "bxN1oZhkB7S2M1PZubRk": { qnum: 119, options: ["Listen with genuine curiosity", "Look for what you have in common", "Respect their path, stay grounded in yours", "Find it interesting but don't engage deeply"] },
    // Q120: The spiritual question you sit with most often:
    "IVHsp3CDMOy5etiWUnx2": { qnum: 120, options: ["Who is God / what is the divine?", "How should I love better?", "What is my purpose here?", "How do I become a better person?"] },

    // --- Conditional questions (Sets A, B, C, D) ---
    // srConditional_QA1: When your child or child-in-your-care has a meltdown, your first instinct is to:
    "LCz8qH4mG9pGhcOoGfN3": { conditionalKey: "srConditional_QA1", options: ["A) Stay calm and let them feel it. Wait for the wave to pass.", "B) Engage immediately. Talk through what they're feeling.", "C) Remove them from the situation. Take charge of the environment.", "D) Set the boundary firmly. The behavior needs correcting."] },
    // srConditional_QA2: A child of yours acts in a way that genuinely surprises you. Your dominant reaction is:
    "0JSqKZk0bSf2o5DhKqSz": { conditionalKey: "srConditional_QA2", options: ["A) Curiosity. Why did they do that? What's underneath it?", "B) Concern. Is something wrong I need to know about?", "C) Discipline first. We address the behavior, then talk.", "D) Pause. Don't react until I understand the pattern."] },
    // srConditional_QA3: Your child wants to talk to you, but you're in the middle of something important. The honest answer about what you usually do:
    "sgKEXytkB3pQrJOofwJA": { conditionalKey: "srConditional_QA3", options: ["A) Stop what I'm doing. They take priority.", "B) Tell them I'll be with them in 5 minutes, and I follow through.", "C) Try to listen while I finish, multi-tasking.", "D) Ask them to wait until I'm done, even if it's an hour."] },
    // srConditional_QA4: When your child does something well, you tend to:
    "WQOaVjUHRq4F5uRDvBjl": { conditionalKey: "srConditional_QA4", options: ["A) Tell them directly: \"I'm proud of you. That was good work.\"", "B) Show it through what we do together. Earned celebration time.", "C) Acknowledge it briefly. Don't want them to need constant praise.", "D) Affirm it later, in front of someone else: \"Did you hear what they did?\""] },
    // srConditional_QA5: Your Child is becoming someone different than your expected. Your feel
    "685PrJlUzcgL2qT7okPc": { conditionalKey: "srConditional_QA5", options: ["A curious. I want to see who they actually are.", "A little anxious. I want to make sure they're on a good path.", "Confused. I'm not sure how to relate to this version of them.", "Proud. They're becoming themselves, not me."] },
    // srConditional_QA6: When discipline is needed, your approach leans towards
    "NcMj333gCq0bWFuvOmkX": { conditionalKey: "srConditional_QA6", options: ["Conversation first. We talk about what happened and why", "Consequence. There's a price for the behavior, applied consistently.", "Time-out and pause. Separation, then reset.", "Logical consequence. Connect the choice to a real outcome"] },
    // srConditional_QA7: Faith or spiritual values in your home are: 
    "PyT3LCKBII4UrUnh918u": { conditionalKey: "srConditional_QA7", options: ["The Center. We pray, we read scripture, we go to church together", "Important buy not enforced. I model it; they choose", "Present buy not formal. We talk about meaning when it comes up.", "Less central right now. We focus on character; faith is theirs to find."] },
    // srConditional_QA8: The thing you most fear getting wrong as a parent is: 
    "Cb0oBwwsYpvdyoi2SJuq": { conditionalKey: "srConditional_QA8", options: ["Not being present enough. They'll grow up and I'll miss it.", "Being too strict. They'll resent me or hide who they are.", "Being too soft. They won't have the discipline they need.", "Repeating my own parents' mistakes without seeing it."] },
    // srConditional_QA9: When your child fails at something, you most naturally
    "6HtnVT9aFse4OwtRzKnn": { conditionalKey: "srConditional_QA9", options: ["Comfort them first. Then we talk about what happened.", "Help them see what they can learn. We problem-solve together.", "Let them sit in it. Failure is the teacher.", "Coach them through the recovery. Show them how to get back up."] },
    // srConditional_QB1: When a decision needs to be made and your team is split, your ten to:
    "BfBzZ2dMDUiOJrOJs074": { conditionalKey: "srConditional_QB1", options: ["Make the call yourself. Speed matters.", "Pull the team back together and find consensus.", "Defer to the person closest to the work", "Sleep on it. Decide tomorrow with fresh eyes."] },
    // srConditional_QB10: The version of you as a leader that you most want to become is:
    "kQuoZhcGbww9jhotL1TC": { conditionalKey: "srConditional_QB10", options: ["The strategist. Sees three moves ahead, makes the call, owns it.", "The developer. Multiplies talent. Leaves people stronger than I found them.", "The unifier. Builds a team that operates as one body.", "The shepherd. Cares for each person while still calling them higher."] },
    // srConditional_QB2: Delegation feels:
    "0hVUa5WfNJ5HggENzCvF": { conditionalKey: "srConditional_QB2", options: ["Natural. Other people often do it better than I could.", "Necessary, but I have to fight my impulse to do it myself.", "Hard. Only certain things, to certain people.", "Stressful. I'd rather just handle it."] },
    // srConditional_QB3: When you have to give critical feedback to a direct report, you usually:
    "Kbh8c725Ok6gIR2hr94p": { conditionalKey: "srConditional_QB3", options: ["Open direct. State the issue, then talk solutions.", "Start with what's working, then transition to what needs to change.", "Schedule it formally. Prep what I'm going to say.", "Avoid it as long as I can. It rarely lands well."] },
    // srConditional_QB4: A team member underperforms for the second month in a row. Your move:
    "XU771Csqu2k5t9AuMWIQ": { conditionalKey: "srConditional_QB4", options: ["Direct conversation. Lay out expectations and a 30-day plan.", "Investigate first. What's going on under the surface", "Pair them with a stronger teammate. Mentorship before correction.", "Start documenting. Begin the exit conversation."] },
    // srConditional_QB5: The part of leadership that energizes you most is: Options:
    "T4sTiKA4ne3rJ2ZQ4XQP": { conditionalKey: "srConditional_QB5", options: ["Building the strategy. Seeing what's possible and architecting the path.", "Developing the people. Watching someone level up under my watch.", "Solving the hard problem. The one nobody else can crack.", "Casting the vision. Telling the story of where we're going."] },
    // srConditional_QB6: The part that drains you most is:
    "E3GfOf9H5kCpg3YgfTir": { conditionalKey: "srConditional_QB6", options: ["The interpersonal friction. Mediating between team members.", "The repetition. Saying the same thing over and over.", "The operations. The systems and tracking and detail work.", "The compliance. Reports, paperwork, regulatory stuff."] },
    // srConditional_QB7: When hiring, your instinct gives the most weight to:
    "eV0clDd0z0VX77V8W29b": { conditionalKey: "srConditional_QB7", options: ["Track record. What have they actually done before?", "Fit. How will they mesh with the team?", "Hunger. Do they want this badly enough to grow into it?", "Wiring. Are they built for this kind of work?"] },
    // srConditional_QB8:  Disagreement from a team member feels:
    "rXkcugLOQRnVJ1pT6kqQ": { conditionalKey: "srConditional_QB8", options: ["Welcome. I need people who push back.", "Useful, if it's specific. General complaining is not.", "Uncomfortable but worth processing in private after.", "Frustrating in the moment. I have to remind myself it's not personal."] },
    // srConditional_QB9: Your leadership style with a brand new team member tends to:
    "EzvaLty5ZFTyflfKwl6f": { conditionalKey: "srConditional_QB9", options: ["Give them clear direction. Less ambiguity is better when they're new.", "Ask them what they need. Let them shape the relationship.", "Spend extra time in person early. Build the bond first.", "Let them learn from doing. I step in when they ask."] },
    // srConditional_QC1: When you meet someone you're interested in, your first instinct is to: (5 Options)
    "sas9WB59cm6LGCwwQssS": { conditionalKey: "srConditional_QC1", options: ["Ask them questions. Learn who they are.", "Watch how they treat the server or other people. Character first", "Test compatibility. Talk about something that matters to me.", "Lean into the spark. See if the energy is real before going deep."] },
    // srConditional_QC10: The kind of partnership you're building toward looks like:
    "u4wlG4zLNHz3rSAm21aN": { conditionalKey: "srConditional_QC10", options: ["Two whole people choosing each other every day. Independence and intimacy.", "Best friends first. The romance grows from the friendship.", "Mission partners. We're building something together.", "Sanctuary. Home is where I exhale, with them."] },
    // srConditional_QC2: After a couple of dates, what makes you decide to keep going OR move on:
    "Z5VJvFJ0BpcGBGdHl17n": { conditionalKey: "srConditional_QC2", options: ["How I feel in their presence. Calm and curious means stay.", "Whether the conversations go anywhere real or stay surface.", "How they handle small disappointments or moments of friction.", "Whether our values line up. The big stuff."] },
    // srConditional_QC4: When someone you're dating doesn't text back for a day, you:
    "giZXJ9CCBwqkCvd2Bwbg": { conditionalKey: "srConditional_QC4", options: ["Don't think much of it. They'll get back when they can.", "Notice but don't reach out. Wait to see what happens.", "Send a follow-up by the end of the day. Don't like ambiguity.", "Start wondering if something's wrong with the relationship."] },
    // srConditional_QC5: Conflict or disagreement in a dating relationship feels:
    "U0sBAw8TA64FQ4XPW7Bq": { conditionalKey: "srConditional_QC5", options: ["Like useful information. We're learning each other.", "Necessary but uncomfortable. I'll engage but won't enjoy it.", "A red flag. If it's already this hard, what does the future look like?", "Like a test. How they handle it tells me who they really are."] },
    // srConditional_QC6: How quickly do you want to move from dating to commitment:
    "O9IyjJANPUA0lQ71B5TR": { conditionalKey: "srConditional_QC6", options: ["Slowly. Months of dating before exclusivity.", "Steadily. Once we both know, we know.", "Quickly, if it's right. Why drag it out?", "Depends entirely on the situation. No fixed timeline."] },
    // srConditional_QC7: Vulnerability with someone you're dating feels:
    "EKsnZ0tylMXe4BObJiEv": { conditionalKey: "srConditional_QC7", options: ["Risky but necessary. I push myself to be open.", "Earned. They have to demonstrate trustworthiness first.", "Natural with the right person. I can tell within a few dates.", "Hard. I tend to share carefully, in small pieces over time."] },
    // srConditional_QC8: The non-negotiable that you have learned through past dating is:
    "LB8Ljx5uIIb9jWh0FYWC": { conditionalKey: "srConditional_QC8", options: ["Faith alignment. Either we share the same foundation or we don't.", "Emotional availability. They have to actually be in it.", "Self-awareness. They have to know themselves.", "Mutual respect. How they treat me when they're stressed."] },
    // srConditional_QC9: What you most want a partner to understand about you is:
    "e6BAPC0JKm8szPAtPKZF": { conditionalKey: "srConditional_QC9", options: ["How I show love. My way is not always obvious.", "What I need to feel safe. Without that, I shut down.", "Who I am underneath. The depth, not just the surface.", "My purpose. What I'm building and why."] },
    // srConditional_QD1: The kind of work that gets you out of bed with energy is:
    "WOzcCOBNgAuHEleLixh7": { conditionalKey: "srConditional_QD1", options: ["A) Work that solves a hard problem. The harder the puzzle, the better.", "B) Work that helps people directly. I want to see the change in their face.", "C) Work that builds something new. I'd rather create than maintain.", "D) Work that runs well. Steady, predictable, the system humming."] },
    // srConditional_QD10: The version of yourself professionally that you most want to become is:
    "wtFvKEWcnZjSzECmxBir": { conditionalKey: "srConditional_QD10", options: ["A) The expert. The one people call when nobody else has the answer.", "B) The builder. The one who creates something that outlasts them.", "C) The mentor. The one who develops the people around them.", "D) The steward. The one who runs the operation well, year after year."] },
    // srConditional_QD2: Your ideal work environment looks like:
    "nnlgWFYXpv1DbR98yLTG": { conditionalKey: "srConditional_QD2", options: ["A) Mostly heads-down focus, with people I trust nearby when I need them.", "B) Lots of conversation and movement. Energy keeps me sharp.", "C) Independent and remote. I work best on my own terms.", "D) Mission-driven team. Long hours are fine if the work matters."] },
    // srConditional_QD3: How you actually run your day at work tends to be:
    "6EXsl8fPZXOAF1SIZpep": { conditionalKey: "srConditional_QD3", options: ["A) Calendar-driven. Plan the week, work the plan.", "B) Priority-driven. I know the top three things and protect time for them.", "C) Reactive in a good way. I respond to what shows up and prioritize on the fly.", "D) Energy-driven. I work on what I have the focus for, when I have it."] },
    // srConditional_QD4: The professional outcome you most want in the next five years is:
    "BlsYjUSKJtMfJtFTAQGH": { conditionalKey: "srConditional_QD4", options: ["A) Mastery in my craft. I want to be the person others come to.", "B) A bigger platform. More impact, more people reached.", "C) Freedom. The kind of work that lets me live the life I actually want.", "D) Stability. Solid income, predictable schedule, room to breathe."] },
    // srConditional_QD5: When work spills into personal life, you:
    "kvY636DbsCc5Rw2JBGab": { conditionalKey: "srConditional_QD5", options: ["A) Let it. The work matters, and the people who love me understand.", "B) Resist it. I draw a hard line. After-hours is sacred.", "C) Manage it case by case. Some weeks bend, others don't.", "D) Struggle with it. I want the boundary but rarely hold it."] },
    // srConditional_QD6: When there's tension with a coworker, your first move is to:
    "kvucotfqHvWWcDWypjpq": { conditionalKey: "srConditional_QD6", options: ["A) Address it directly with them. The sooner, the cleaner.", "B) Sit with it for a day before saying anything. Make sure I'm reading it right.", "C) Loop in someone neutral first. Get a sanity check before I act.", "D) Try to let it resolve on its own. Most things smooth out over time."] },
    // srConditional_QD7: The thing that has held your career back most so far is:
    "glfIDP1099UDzsrTIFDq": { conditionalKey: "srConditional_QD7", options: ["A) Not enough exposure. The right people don't know what I can do.", "B) Not enough focus. I've chased too many things at once.", "C) Not enough courage. I stayed safe when I should have moved.", "D) Not enough margin. Life pressures kept me in survival mode."] },
    // srConditional_QD8: The hardest career decision you have faced or are facing is about:
    "YyZ0TDAbVKuNfPzkpFS6": { conditionalKey: "srConditional_QD8", options: ["A) Money versus meaning. Taking the pay cut to do the work I actually want.", "B) Stability versus risk. Leaving something secure to try something new.", "C) Loyalty versus growth. Staying with people I owe or moving for the next step.", "D) Visibility versus depth. Going public with my work or keeping it private and deep."] },
    // srConditional_QD9: When it comes to faith and your professional life:
    "ljIpaoAPWbTjDgBPOtT9": { conditionalKey: "srConditional_QD9", options: ["A) Faith is the foundation. My work is part of how I live it out.", "B) Faith is private but present. It shapes me, but I do not bring it into the office.", "C) Faith is something I am still figuring out alongside the work.", "D) Faith and work are separate worlds for me, and I prefer it that way."] },
    // srConditional_QE1: When you and your spouse hit a recurring disagreement, what tends to be true:
    "xME69riTiKkzqKCAm1sM": { conditionalKey: "srConditional_QE1", options: ["A) We have the same fight, over and over. The topics change; the dance is the same.", "B) We rarely fight outright. Things go unsaid and build up.", "C) We blow up, then make up fast. The intensity passes within hours.", "D) Conflict is rare and short. We mostly avoid it on purpose."] },
    // srConditional_QE10: The marriage you want to build over the next ten years looks like:
    "gqtVO66NLS2vsecZ77ws": { conditionalKey: "srConditional_QE10", options: ["A) Deeper than what we have now. Same direction, more intimacy.", "B) A partnership with shared mission. We are building something together.", "C) A sanctuary. Home is where we exhale together.", "D) Steady and faithful. A long, slow, well-tended thing."] },
    // srConditional_QE2: When you and your spouse hit a real disagreement, your default move is to:
    "u24t0n4ss8lgYrzU8ATI": { conditionalKey: "srConditional_QE2", options: ["A) Press in. Talk it through until we land somewhere.", "B) Pull back. Take time alone to think, come back later.", "C) Lead with the fix. Offer what would make it better and move forward.", "D) Bring in the facts. Lay out what happened and where the breakdown was."] },
    // srConditional_QE3: The intimacy in your marriage right now is:
    "GSEmuqBHLDTluFpdgJJh": { conditionalKey: "srConditional_QE3", options: ["A) Strong. We are close emotionally and physically.", "B) Steady but not what it used to be. We have drifted some.", "C) Imbalanced. One area is alive, the other has gone quiet.", "D) Distant. There is more space between us than either of us wants."] },
    // srConditional_QE4: When a big decision shows up (move, money, kids, career, faith), the two of you tend to:
    "KG3LMoGgvoDZ7B027YwG": { conditionalKey: "srConditional_QE4", options: ["A) Talk it through together until we are aligned, then act.", "B) One of us takes the lead and the other supports the call.", "C) Stall it. Decisions sit on the shelf longer than they should.", "D) Each have our own view and either compromise or hold ground."] },
    // srConditional_QE5: The thing your spouse does that lands as love for you, but you do not always recognize as love in the moment:
    "3z8avJ5xAnxwjfBqFDq6": { conditionalKey: "srConditional_QE5", options: ["A) The way they handle things without me asking.", "B) The way they say things they did not have to say.", "C) The way they show up physically when I am worn down.", "D) The way they remember the small stuff I mention in passing."] },
    // srConditional_QE6: The gap between how you try to love your spouse and how they actually need to be loved is:
    "VhVPVudFgIfG0BpRaOTU": { conditionalKey: "srConditional_QE6", options: ["A) Wide. I now realize we have spent years speaking different currencies.", "B) Real but bridgeable. We see it and are working on it.", "C) Mostly closed. We have learned each other, and we mostly hit the right notes.", "D) I am not sure. We have never really mapped what each of us needs."] },
    // srConditional_QE7: When the marriage hits a stretch of stress (kids, work, money, health, loss), the two of you tend to:
    "Ui0D4haJEVmpxbPd8Ml5": { conditionalKey: "srConditional_QE7", options: ["A) Pull closer. The hard thing becomes ours, not mine and theirs.", "B) Pull apart, and have to rebuild after. We retreat to cope.", "C) One of us carries it, and the other waits to be told what is needed.", "D) Argue about how to handle the stress before we handle the stress."] },
    // srConditional_QE8: The first thing you notice when your marriage is starting to drift:
    "jBY1S4nx3HETQmHLuqGw": { conditionalKey: "srConditional_QE8", options: ["A) The conversations get shorter. Less talk about the real stuff.", "B) The physical closeness fades. Less touch, less sex, less proximity.", "C) The fights get sharper or the silences get longer.", "D) The plans for the future stop coming up. We stop talking about what is next."] },
    // srConditional_QE9: Vulnerability with your spouse versus other people in your life feels:
    "MCBNHF8kuxOvoENsomwa": { conditionalKey: "srConditional_QE9", options: ["A) Easier with them than with anyone else. They are my safest person.", "B) Harder with them than I would like. Old wounds make me cautious.", "C) About even. They are one of several safe people in my life.", "D) Harder with them than with others. We have work to do here."] },
  },

  // Question number to pillar lookup.
  PILLAR_BINS: {
    behaviorProfile   : [  1,  24],
    personalityCode   : [ 25,  52],
    actionStyle       : [ 53,  72],
    connectionCurrency: [ 73,  92],
    learningChannel   : [ 93, 108],
    spiritualCompass  : [109, 120],
  },

  // Pillar 2 (Personality Code): for each question, which dichotomy slot it belongs
  // to and the SR letter at option position 0 and 1.
  // Dichotomy slot keys are legacy (ei/sn/tf/jp) and never customer facing.
  // Letters map to the SR system:
  //   ei -> Charge: O (Outward) vs W (Inward)
  //   sn -> Trust:  T (Tangible) vs V (Vision)
  //   tf -> Decide: M (Mind)     vs H (Heart)
  //   jp -> Live:   P (Plan)     vs F (Flow)
  PERSONALITY_QUESTION_INFO: {
    25: { dichotomy: "ei", tags: ["O", "W"] },
    26: { dichotomy: "sn", tags: ["T", "V"] },
    27: { dichotomy: "tf", tags: ["M", "H"] },
    28: { dichotomy: "jp", tags: ["P", "F"] },
    29: { dichotomy: "ei", tags: ["O", "W"] },
    30: { dichotomy: "sn", tags: ["T", "V"] },
    31: { dichotomy: "tf", tags: ["M", "H"] },
    32: { dichotomy: "jp", tags: ["P", "F"] },
    33: { dichotomy: "ei", tags: ["O", "W"] },
    34: { dichotomy: "sn", tags: ["T", "V"] },
    35: { dichotomy: "tf", tags: ["M", "H"] },
    36: { dichotomy: "jp", tags: ["P", "F"] },
    37: { dichotomy: "ei", tags: ["O", "W"] },
    38: { dichotomy: "sn", tags: ["T", "V"] },
    39: { dichotomy: "tf", tags: ["M", "H"] },
    40: { dichotomy: "jp", tags: ["P", "F"] },
    41: { dichotomy: "ei", tags: ["W", "O"] },
    42: { dichotomy: "sn", tags: ["T", "V"] },
    43: { dichotomy: "tf", tags: ["M", "H"] },
    44: { dichotomy: "jp", tags: ["P", "F"] },
    45: { dichotomy: "ei", tags: ["O", "W"] },
    46: { dichotomy: "sn", tags: ["T", "V"] },
    47: { dichotomy: "tf", tags: ["M", "H"] },
    48: { dichotomy: "jp", tags: ["P", "F"] },
    49: { dichotomy: "ei", tags: ["O", "W"] },
    50: { dichotomy: "sn", tags: ["T", "V"] },
    51: { dichotomy: "tf", tags: ["M", "H"] },
    52: { dichotomy: "jp", tags: ["P", "F"] },
  },

  // Pillar 6 Q109 faith orientation: ordered short labels by option position.
  FAITH_ORIENTATION_LABELS: [
    "Christian (any tradition)",
    "Spiritual but not specifically religious",
    "Other major faith tradition",
    "Secular but open",
    "Still figuring out",
  ],
};
